# -*- coding: utf-8 -*-
"""PhanHuynhQuocBao_TTNTchieuCN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rf6BHtxuYTIc4c1SunDev-IMvmOhLEHo
"""

#1
a = input("nhap so thu nhat: ")
b = input("nhap so thu hai: ")
tong = int(a) + int(b)
hieu = int(a) - int(b)
tich = int(a) * int(b)
thuong = int(a) / int(b)
print(tong)
print(hieu)
print(tich)
print(thuong)

#4
a = input("nhap so thu nhat: ")
b = input("nhap so thu hai: ")
if a > b:
  print("1Hello World")
else:
  print("0")

#5
a = input("nhap vao so a: ")
b = input("nhap vao so b: ")
if a == b:
  print("Yes")
else:
  print("No")

#7
a = input("nhao so thu nhat : ")
b = input("nhap so thu hai : ")
d = input("nhap so thu ba : ")
if a == b and b == d:
  print("hello world")
else:
  print(0)

#8
a = input("nhao so thu nhat : ")
b = input("nhap so thu hai : ")
c = input("nhap so thu ba : ")
d = input("nhap so thu tu : ")
if a == b or c == d:
  print("hello world")
else:
  print("0")

#9
if a > b: print("Hello World")  else: print("0")

#10
a = input("nhap a : ")
b = input("nhap b : ")
if a > b:
  print("A")
else:
  print("=")
if a == b:
  print("=")
else:
  print("B")

#11
n = int(input("nhap n: "))

a = []
for i in range(n):
    x = int(input(f"a[{i}] = "))
    a.append(x)

b = [x for x in a if x % 2 == 0]

print("\nmang a:", *a)
if b:
    print("mang b (phan tu chan):", *b)
else:
    print("mang b: (khong co phan tu chan)")

#12
total = 0
for x in range(1000):
  if x % 3 == 0 or x % 5 ==0:
    total += x
  print("tong", total)

#13
def tron_mang(a, b):
  ket_qua = []
    n = max(len(a), len(b))
      for i in range(n):
        if i < len(a) and i < len(b):
            ket_qua.append(a[i] + b[i])
        elif i < len(a):
            ket_qua.append(a[i])
        else:
            ket_qua.append(b[i])

    return ket_qua


a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]

ket_qua = tron_mang(a, b)

print("mang a:      ", a)
print("mang b:      ", b)
print("mang ket qua:", ket_qua)

#14